### ISSUE TITLE
"Bundle" the extension and check excludes

### ISSUE THREAD

**Issue by apjanke** [apjanke/vscode-octave-hacking#19]
`vsce package` is saying this:

```
[vscode-octave-hacking] $ vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> octave-hacking@0.2.13-SNAPSHOT vscode:prepublish
> npm run compile

> octave-hacking@0.2.13-SNAPSHOT compile
> tsc -p ./

This extension consists of 2032 files, out of which 1642 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /Users/janke/repos/vscode-octave-hacking/octave-hacking-0.2.13-SNAPSHOT.vsix (2032 files, 3.19MB)
[vscode-octave-hacking] $
```

Let's do that.

## TODO

* [x] Update the excludes.
* [x] Learn about the various bundlers: webpack, esbuild, rollup.js and pick one.
* [x] Bundle the extension.
* [x] Update the excludes after bundling.

## References

* [Bundling an Extension](https://code.visualstudio.com/api/working-with-extensions/bundling-extension)
* [Excluding Files from an Extension](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#.vscodeignore)

**Comment by apjanke** [comment]
Done in https://github.com/apjanke/vscode-octave-hacking/commit/f16d95a2ac937391ab719c790426166cb394b0a7.
